
version: '3'

### Services
services:
  ### Web Server Container
  ecp:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ecp
    restart: always
    tty: true
    working_dir: /var/www
    ports:
       - "6080:80"
    volumes:
      - ./:/var/www
      - ./php-fpm/php.ini:/etc/php/7.4/fpm/php.ini
    networks:
      - ecp-network

# Networks
networks:
    ecp-network:
      driver: bridge