version: '3'

### Services
services:
  ### Web Server Container
  ecp_server:
    image: 192.168.0.137:5000/ecp.server
    container_name: ecp_server
    restart: always
    tty: true
    working_dir: /var/www
    ports:
       - "6080:80"
    volumes:
      - ./:/var/www
      - ./php-fpm/php.ini:/etc/php/7.4/fpm/php.ini
    networks:
      - ecp_server

# Networks
networks:
    ecp_server:
      driver: bridge